### ISSUE TITLE
[Bug]: "Dirty" YAML will cause file to be ignored when generating graph

### ISSUE THREAD

**Issue by 7Mik** [ObsidianPublisher/follow_template#6]
### Material General discussion

- [X] My issue is not a question relative to [Material Mkdocs](https://squidfunk.github.io/mkdocs-material/) nor [Mkdocs](https://www.mkdocs.org/) (*[You can open a discussion to get more help!](https://github.com/squidfunk/mkdocs-material/discussions)*)
- [X] I checked the issue to prevent duplicate
- [X] I checked my configurations files and the documentation
- [X] My issue is not relative to the [actions/github Workflow](https://github.com/ObsidianPublisher/actions). If it's the case, you must open an issue [here](https://github.com/ObsidianPublisher/actions/issues).
- [X] My issue is not relative to the **Obsidian Plugin**. If it's the case, you must open an issue [here](https://github.com/ObsidianPublisher/obsidian-github-publisher/issues).

### Error

```bash session
Front matter not populated for Gastro.md: ParserError(None, None, 'did not find expected <document start>', <yaml._yaml.Mark object at 0x0000014239CCDF30>)
```

### Bug description

A "dirty" YAML will cause the file to be skipped

### Steps to reproduce

---
title: Paramyxoviridae ssRNA- env
updated: 2023-02-01T20:35:07.0000000+01:00
created: 2023-01-11T22:07:12.0000000+01:00
 
  - 
dg-publish: true
sticker: emoji//1f49d
---

This is an example of a dirty yaml, with extra spaces

### Requirements

```bash session
mkdocs==1.5.3
mkdocs-material==9.5.3
mkdocs-ezlinked-plugin==0.3.3
mkdocs-awesome-pages-plugin==2.9.2
mdx_breakless_lists==1.0.1
mkdocs-embed-file-plugins==2.0.9
mkdocs_custom_fences==0.1.2
mkdocs-git-revision-date-localized-plugin==1.2.2
mkdocs-encryptcontent-plugin==3.0.1
mkdocs-callouts==1.10.0
mkdocs-custom-tags-attributes==0.3.1
mkdocs-static-i18n==1.2.0
mkdocs-meta-descriptions-plugin==3.0.0
mkdocs-glightbox==0.3.6
mkdocs-minify-plugin==0.7.2
mkdocs-exclude==1.0.2

obsidiantools==0.10.0
pyvis==0.3.2
```

### Mkdocs.yml

```YAML
site_name: My Digital Garden
site_description: WIP
site_url: *redacted* # Change this to your site URL
site_author: Michele

theme:
    name: 'material'
    logo: assets/meta/favicons.png
    favicon: assets/meta/favicons.png
    custom_dir: overrides
    font:
        text: Ubuntu
        code: Ubuntu Mono
    language: IT
    palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    features:
        - navigation.indexes
        - navigation.top
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.expand
        - search.suggest
        - search.highlight

# Extensions
markdown_extensions:
  - footnotes
  - nl2br
  - attr_list
  - sane_lists
  - meta
  - smarty
  - tables
  - mdx_breakless_lists
  - def_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
  - pymdownx.tasklist:
       custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - toc:
      permalink: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
plugins:
  - search
  - meta-descriptions
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
      locale: IT
      custom_format: "%A %d %B %Y"
      enable_creation_date: true
  - ezlinks:
        wikilinks: true
  - awesome-pages
  - embed_file:
      callouts: true
      custom-attributes: 'assets/css/custom_attributes.css'
  - custom-attributes:
      file: 'assets/css/custom_attributes.css'
  - tags:
      tags_file: tags.md
  - encryptcontent:
      title_prefix: '🔐'
      summary: 'Private page'
      placeholder: 'Password'
      decryption_failure_message: 'Invalid password'
      encryption_info_message: "You don't have access to this page."
      search_index: 'encrypted'
      password_button: True
      password_button_text: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" height="1em" width="1em"><!--! Font Awesome Pro 6.1.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. --><path d="M416 32h-64c-17.67 0-32 14.33-32 32s14.33 32 32 32h64c17.67 0 32 14.33 32 32v256c0 17.67-14.33 32-32 32h-64c-17.67 0-32 14.33-32 32s14.33 32 32 32h64c53.02 0 96-42.98 96-96V128C512 74.98 469 32 416 32zM342.6 233.4l-128-128c-12.51-12.51-32.76-12.49-45.25 0c-12.5 12.5-12.5 32.75 0 45.25L242.8 224H32C14.31 224 0 238.3 0 256s14.31 32 32 32h210.8l-73.38 73.38c-12.5 12.5-12.5 32.75 0 45.25s32.75 12.5 45.25 0l128-128C355.1 266.1 355.1 245.9 342.6 233.4z"/></svg>'
  - callouts
  - glightbox
hooks:
  - overrides/hooks/on_page_markdown.py
  - overrides/hooks/on_env.py
  - overrides/hooks/on_files.py
extra_javascript:
  - https://cdn.jsdelivr.net/gh/ObsidianPublisher/assets@main/dist/javascript.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
    - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css
    - https://cdn.jsdelivr.net/gh/ObsidianPublisher/assets@main/dist/styles.css
    - assets/css/admonition.css
    - assets/css/custom_attributes.css
    - assets/css/customization.css
extra:
  SEO: assets/meta/SEO.png
  comments: False #disable comments globally
  generate_graph: true #generate the graph of the site
  attachments: 'assets/img' #path to the folder where the attachments are stored
  no-auto-h1: False #disable the automatic generation of h1 if no h1 is found
  blog_list:
    pagination: true #enable pagination
    pagination_message: true #display the message "Showing x posts out of y"
    pagination_translation: 'posts in' #message to display before the number of posts ; Add your own translation!
    no_page_found: "No pages found!" #message to display when no pages are found ; Add your own translation!
  hooks:
    strip_comments: true
    fix_heading: true
```
